config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries
  resources :accounts
  resources :items
  resources :units
  resources :transaktions
  resources :entities

  root "transaktions#new"

  get "items/:id/accounts" => "items#accounts"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :transaktion
  belongs_to :item
  belongs_to :account

  def net_amt
    if self.price and self.qty
      pq = self.price*self.qty/100
      pq *= -1 if not self.is_debit
      pq
    else
      0
    end
  end

  def entry_date
    Transaktion.find(self.transaktion_id).date
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:transaktion_id, :item_id, :price, :qty, :is_debit, :account_id)
    end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaktion_id %><br>
    <%= f.text_field :transaktion_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.text_field :qty %>
  </div>
  <div class="field">
    <%= f.label :is_debit %><br>
    <%= f.check_box :is_debit %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journal</h1>

<table>
  <thead>
    <tr>
      <th>transaction</th>
      <th>item</th>
      <th>price</th>
      <th>qty</th>
      <th>dr</th>
      <th>cr</th>
      <th>account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% prev_tx = "" %>
    <% entries = Entry.all.sort_by(&:transaktion_id) %>
    <% entries.each do |entry| %>
      <% transaktion = Transaktion.find(entry.transaktion_id) %>
      <% if entry.transaktion_id != prev_tx %>
       <tr class="transaktion">
        <td colspan="2">
         <%= transaktion.date.to_s.slice(0,10) %>
        </td>
        <td colspan="6">
         <% if transaktion.entity_id %>
          <% entity = Entity.find(transaktion.entity_id) %>
          <a href="<%= entity_path entity %>"><%= entity.name %></a>
         <% end %>
        </td>
       </tr>
      <% end %>
      <% prev_tx = entry.transaktion_id %>
      <tr>
        <td>
          <a href="<%= transaktion_path transaktion %>"><%= entry.transaktion_id %></a>
        </td>
        <td>
         <% if entry.item_id %>
          <% item = Item.find(entry.item_id) %>
          <a href="<%= item_path item %>"><%= item.gendesc %></a>
         <% end %>
        </td>
        <td class="currency"><%= "%.2f"%(entry.price.to_f/100) %></td>
        <td class="qty">@<%= entry.qty %></td>
        <% net = entry.net_amt %>
        <td class="currency net"><%= "%.2f"%net if net > 0 %></td>
        <td class="currency net"><%= "%.2f"%(-net) if net < 0 %></td>
        <td>
	 <% if entry.account_id %>
	  <% account = Account.find(entry.account_id) %>
          <a href="<%= account_path account %>"><%= account.account_pathname %></a>
	 <% end %>
        </td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaktion', new_transaktion_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction:</strong>
  <%= @entry.transaktion %>
</p>

<p>
  <strong>Item:</strong>
  <%= @entry.item %>
</p>

<p>
  <strong>Price:</strong>
  <%= @entry.price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @entry.qty %>
</p>

<p>
  <strong>Is debit:</strong>
  <%= @entry.is_debit %>
</p>

<p>
  <strong>Account:</strong>
  <%= Account.find(@entry.account_id).account_pathname %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>