config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries
  resources :accounts
  resources :items
  resources :units
  resources :transaktions
  resources :entities

  root "transaktions#new"

  get "items/:id/accounts" => "items#accounts"

end

app/models/transaktion.rb
class Transaktion < ActiveRecord::Base
  belongs_to :entity
end

app/controllers/transaktions_controller.rb
class TransaktionsController < ApplicationController
  before_action :set_transaktion, only: [:show, :edit, :update, :destroy]

  # GET /transaktions
  # GET /transaktions.json
  def index
    @transaktions = Transaktion.all
  end

  # GET /transaktions/1
  # GET /transaktions/1.json
  def show
  end

  # GET /transaktions/new
  def new
    @transaktion = Transaktion.new
    # Make data available for option pulldowns:
    # TODO At some point (when massively many items are on file)
    # we will do this w. AJAX
    @entities = Entity.all
    @items = Item.all
    @units = Unit.all
    @accounts = Account.all
    @page_title
  end

  # GET /transaktions/1/edit
  def edit
  end

  # POST /transaktions
  # POST /transaktions.json
  def create
    params.permit!
    @transaktion = Transaktion.new(params["transaktion"])
    @transaktion.save # see http://stackoverflow.com/a/2618902/948073 
    params["entry"].keys.each do |index|
      entry = params["entry"][index]
      puts entry
      if entry["account_id"]
	  entry["qty"] = 1 if not entry["qty"]
	  # price is an integer field, measured in pennies...
	  is_debit = (index.to_i%2 != 0)
	  entry["is_debit"] = is_debit
	  price = (100.0*(entry["price"].to_f)+0.5).to_s
	  entry["price"] = price
	  entry["transaktion_id"] = @transaktion.id
	  Entry.new(entry).save
      end
    end

    respond_to do |format|
      if @transaktion.save
        format.html { redirect_to @transaktion, notice: 'Transaktion was successfully created.' }
        format.json { render :show, status: :created, location: @transaktion }
      else
        format.html { render :new }
        format.json { render json: @transaktion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaktions/1
  # PATCH/PUT /transaktions/1.json
  def update
    respond_to do |format|
      if @transaktion.update(transaktion_params)
        format.html { redirect_to @transaktion, notice: 'Transaktion was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaktion }
      else
        format.html { render :edit }
        format.json { render json: @transaktion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaktions/1
  # DELETE /transaktions/1.json
  def destroy
    entries = Entry.where transaktion_id: @transaktion.id
    # Why is the following not done automatically?
    entries.each do |entry|
     entry.destroy
    end
    @transaktion.destroy
    respond_to do |format|
      format.html { redirect_to transaktions_url, notice: 'Transaktion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaktion
      @transaktion = Transaktion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaktion_params
      params.require(:transaktion).permit(:date, :entity_id, :is_void)
    end
end

app/helpers/transaktions_helper.rb
module TransaktionsHelper
end

app/views/transaktions/_form.html.erb
<%= form_for(@transaktion) do |f| %>
  <% if @transaktion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaktion.errors.count, "error") %> prohibited this transaktion from being saved:</h2>

      <ul>
      <% @transaktion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :entity_id %><br>
    <%= f.text_field :entity_id %>
  </div>
  <div class="field">
    <%= f.label :is_void %><br>
    <%= f.check_box :is_void %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaktions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaktion %> |
<%= link_to 'Back', transaktions_path %>

app/views/transaktions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Entity</th>
      <th>Is void</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaktions.each do |transaktion| %>
      <tr>
        <td><%= transaktion.date.strftime("%B %d, %Y") if transaktion.date %></td>
        <td><strong><%= Entity.find(transaktion.entity_id).name if transaktion.entity_id %></strong></td>
        <td><%= transaktion.is_void %></td>
        <td><%= link_to 'Show', transaktion %></td>
        <td><%= link_to 'Edit', edit_transaktion_path(transaktion) %></td>
        <td><%= link_to 'Destroy', transaktion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaktion_path %>

app/views/transaktions/new.html.erb
<h1>enter new purchase transaktion</h1>
<%= form_for :transaktion, url: "/transaktions" do |f| %>

 <fieldset id="pos">
  <legend>point of sale information</legend>
  <label for="date">date</label>

  <%= f.text_field :date, :id => "date", :tabindex => 1 %><br />
  <!--
   For input elements for foreign key properties, the actual Rails input
   element (that will be included in params) is a hidden element, so the
   autocomplete element for user input can display "friendly" names instead of
   numeric keys.
  -->
  <label>other party to transaktion</label>
  <%= autofill_inputs "transaktion", nil, "entity" %>

 </fieldset>

 <fieldset id="payments">
  <legend>payments</legend>

  <div id="credits">
  <!-- data-index even for credit, odd for debit -->
  <!-- <fieldset class="payment_method replic" id="payment_method"> -->
  <fieldset class="payment_method entry replic">

   <!-- account -->
   <label>paid from account</label>
   <%= autofill_inputs "entry", 0, "account" %>
   <!-- amount -->
   <label>credit amount</label>
   <input name="entry[0][price]" class="money credit multiplicand" />

  </fieldset>
  </div>

  <button class="replicator" type="button" data-fieldset-type="payment_method">additonal payment method</button>

 </fieldset>

 <fieldset id="purchases">
  <legend>purchaes this transaktion</legend>
  <table><thead>
   <tr><th>item</th><th>price</th><th>qty</th><th>account</th><th>debit amount</th></tr>
  </thead><tbody id="debits">

  <!-- <tr id="item" class="entry_item replic"> -->
  <tr class="entry_item entry replic">
   <!-- item -->
   <!-- TODO: increment numbers in id attributes, too -->
   <!-- TODO: blank out filled-in fields, too -->
   <td>
    <%= autofill_inputs "entry", 1, "item" %>
   </td>
   <!-- price -->
   <td><input id="entry_1_price" name="entry[1][price]" class="money multiplicand" /></td>
   <!-- qty -->
   <td><input id="entry_1_qty" name="entry[1][qty]" class="multiplicand" value="1" /></td>
   <!-- acct -->
   <td>
    <%= autofill_inputs "entry", 1, "account" %>
   </td>
   <td>
    <input id="entry_1_debit" class="money debit" disabled />
   </td>
  </tr>

  <tbody></table>

  <button class="replicator" type="button" data-fieldset-type="entry_item">additional item</button>

 </fieldset>

 <%= f.submit "post transaktion", :id => "post", :disabled => true %>

<% end %>

<table id="summary">
<thead>
<tr><th>total debits</th><th>total credits</th><th>imbalance</th></tr>
</thead>
<tbody>
<tr><td id="total_debits" class="money">0.00</td><td id="total_credits" class="money">0.00</td><td id="imbalance" class="money">0.00</td></tr>
</tbody>
</table>

<div id="entity_popup" class="popup">
 <%= render "entities/new" %>
</div>
<!-- TODO: Don't repeat yourself: -->
<div id="account_popup" class="popup">
 <%= render "accounts/new" %>
</div>
<div id="item_popup" class="popup">
 <%= render "items/new" %>
</div>

app/views/transaktions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="instance">
  <%= @transaktion.date %><br />

  <% if @transaktion.entity_id %>
   <% entity = Entity.find(@transaktion.entity_id) %>
   <h1><a href="<%= entity_path entity %>"><%= entity.name %></a></h1>
  <% end %>

  <table class="entries">
   <thead>
    <tr>
     <th>item</th>
     <th>account</th>
     <th>debit amt</th>
     <th>credit amt</th>
     <th></th>
    </tr>
   </thead>
   <tbody>
    <% entries = Entry.where(transaktion_id: @transaktion.id).sort { |x, y| %>
     <% y.net_amt <=> x.net_amt %>
    <% } %>
    <% entries.each do |entry| %>
     <tr>
      <% item = Item.find(entry.item_id) if entry.item_id %>
      <td><a href="<%= item_path item if item %>"><%= item.gendesc if item %></a></td>
      <% account = Account.find(entry.account_id) %>
      <td><a href="<%= account_path account %>"><%= account.account_pathname %></a></td>
      <td class="money"><%= "%.2f"%(entry.price*entry.qty/100) if entry.is_debit %></td>
      <td class="money"><%= "%.2f"%(entry.price*entry.qty/100) if not entry.is_debit %></td>
      <td>
      <a href="<%= edit_entry_path entry %>">
      edit
      </a>
      </td>
     </tr>
    <% end %>
   </tbody>
  </table>
  <%= link_to "Edit", edit_transaktion_path(@transaktion) %> |
  <%= link_to "New", new_transaktion_path %>
</div>