config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries
  resources :accounts
  resources :items
  resources :units
  resources :transaktions
  resources :entities

  root "transaktions#new"

  get "items/:id/accounts" => "items#accounts"

end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
    genericResponse @entities
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @entities = Entity.all
    @transaktions = Transaktion.all
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create

    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json {
         render json: {id: @entity.id, friendlyName: friendlyName(@entity), input: params[:input]}
        }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:name, :no, :frac, :unit, :street, :box, :city, :polsub, :postal, :nation, :phone, :email, :url)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :no %><br>
    <%= f.number_field :no %>
  </div>
  <div class="field">
    <%= f.label :frac %><br>
    <%= f.text_field :frac %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_area :unit %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_area :street %>
  </div>
  <div class="field">
    <%= f.label :box %><br>
    <%= f.text_area :box %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </div>
  <div class="field">
    <%= f.label :polsub %><br>
    <%= f.text_area :polsub %>
  </div>
  <div class="field">
    <%= f.label :postal %><br>
    <%= f.text_area :postal %>
  </div>
  <div class="field">
    <%= f.label :nation %><br>
    <%= f.text_area :nation %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/_new.html.erb
<%= form_for :entity, url: "/entities" do |f| %>
 <legend>new business entity</legend>
 <fieldset>
  <legend>name</legend>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => "true", :tabindex => 1 %>
 </fieldset>

 <fieldset>
  <legend>address</legend>
  <%= f.label :no, "number" %>
  <%= f.text_field :no, :tabindex => 2 %>
  <%= f.label :frac, "fraction, e.g. 1/2" %>
  <%= f.text_field :frac %>
  <%= f.label :street, "street" %>
  <%= f.text_field :street, :tabindex => 3 %>
  <%= f.label :unit, "unit, e.g. Suite 100" %>
  <%= f.text_field :unit %><br />
  <%= f.label :box, "box" %>
  <%= f.text_field :box %><br />
  <%= f.label :city, "city" %>
  <%= f.text_field :city, :tabindex => 4 %>
  <%= f.label :polsub, "state (or province, etc.)" %>
  <%= f.text_field :polsub, :tabindex => 5 %>
  <%= f.label :postal, "zip code (or other postal code)" %>
  <%= f.text_field :postal, :tabindex => 6 %><br />
  <%= f.label :nation , "country" %>
  <%= f.text_field :nation, :tabindex => 7 %>
 </fieldset>

 <fieldset>
  <legend>other contact info</legend>
  <%= f.label :phone, "phone" %>
  <%= f.text_field :phone, :tabindex => 8 %><br />
  <%= f.label :email, "email" %>
  <%= f.text_field :email, :tabindex => 9 %><br />
  <%= f.label :url, "url" %>
  <%= f.text_field :url, :tabindex => 10 %>
 </fieldset>

 <%= f.submit :tabindex => 11 %>

<%  end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>No</th>
      <th>Frac</th>
      <th>Unit</th>
      <th>Street</th>
      <th>Box</th>
      <th>City</th>
      <th>Polsub</th>
      <th>Postal</th>
      <th>Nation</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= link_to entity.name, entity_path(entity) %></td>
        <td><%= entity.no %></td>
        <td><%= entity.frac %></td>
        <td><%= entity.unit %></td>
        <td><%= entity.street %></td>
        <td><%= entity.box %></td>
        <td><%= entity.city %></td>
        <td><%= entity.polsub %></td>
        <td><%= entity.postal %></td>
        <td><%= entity.nation %></td>
        <td><%= entity.phone %></td>
        <td><%= entity.email %></td>
        <td><%= entity.url %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<%= render "entities/new" %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<div>

 <p class="address">
  <strong><%= @entity.name %></strong>
  <% if @entity.street != "" %>
   <br />
   <%= "#{@entity.no} #{@entity.frac} #{@entity.street}" %><br />
  <% end %>
  <% if @entity.unit != "" %>
   <%= @entity.unit %><br /> 
  <% end %>
  <% if @entity.box != "" %>
  <%= "PO Box #{@entity.box}" %><br />
  <% end %>
  <% if (@entity.city) != "" %>
   <%= @entity.city %><%= ", #{@entity.polsub}" if @entity.polsub != "" %>
   <%= " #{@entity.postal}" if @entity.postal != "" %>
  <% end %>
  <% if @entity.nation != "" %>
   <br />
   <%= @entity.nation %>
  <% end %>
 </p>

 <% if @entity.phone || @entity.email || @entity.url %>
  <p>
   <% if @entity.phone != "" %>
    <%= @entity.phone %>
    <br />
   <% end %>
   <% if @entity.email != "" %>
    <%= mail_to @entity.email %>
    <br />
   <% end %>
   <% if @entity.url != "" %>
    <%= link_to @entity.url, @entity.url %>
    <br />
   <% end %>
  </p>
 <% end %>

</div>

<% # TODO place list of transactions with this entity here %>
<div>

 <ul>
 <% @transaktions.where(entity_id: @entity.id).order(:date).reverse.each do |transaktion| %>
  <li>
   <%= link_to transaktion.date, transaktion_path(transaktion) %>
  </li>
 <% end %>
 </ul>

</div>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>