config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :entries
  resources :accounts
  resources :items
  resources :units
  resources :transaktions
  resources :entities

  root "transaktions#new"

  get "items/:id/accounts" => "items#accounts"

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :account

  # Get the full pathname of an account
  def account_pathname
    account_fullname = self.name
    account_level = self
    loop do
      break if not account_level.account_id
      account_level = Account.find(account_level.account_id)
      break if account_level == self # closed loop detection TODO make it a DB constraint
      account_fullname = "#{account_level.name}|#{account_fullname}"
    end
    account_fullname
  end

  def balance
    tally = 0
    Entry.where(account_id: self.id).each do |entry|
      tally += entry.net_amt
    end
    tally
  end

  def self.columnize
    copy = Array.new(self.all)
    left_column = []
    right_column = []
    while copy.length > 0
      acct = copy.shift
      if acct.account_pathname.start_with? "assets"
        left_column.push acct
      else
        right_column.push acct
      end
    end
    [left_column, right_column].map {|column|
     column.sort {|x, y|
      x.account_pathname <=> y.account_pathname
     }
    }
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
    genericResponse @accounts
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @accounts = Account.all # line added by Lori
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        if params["date"] && params["init"]
          # identify opening balances account
          openingBalancesAccount = Account.find_by name: "opening balances"
          # create transaction which initializes account balance:
          transaktion = {}
          transaktion["date"] = params["date"]
          transaktion["is_void"] = false
          tr = Transaktion.new(transaktion)
          tr.save
          # create two entries for account-initializing transaction:
          debit = {}
          debit["account_id"] = @account.id
          debit["transaktion_id"] = tr.id
          debit["price"] = params["init"]
          debit["qty"] = 1
          debit["is_debit"] = true
          Entry.new(debit).save
          credit = debit
          credit["account_id"] = openingBalancesAccount.id
          credit["is_debit"] = false
          Entry.new(credit).save
        end
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json {
         render json: {id: @account.id, friendlyName: friendlyName(@account), input: params[:input]}
        }
      else
        # format.html { render :new }
        # format.json { render json: @account.errors, status: :unprocessable_entity }
        render "new"
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :number, :account_id)
    end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_area :number %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_new.html.erb
<%= form_for :account, url: "/accounts"  do |f| %>

 <fieldset>

  <legend>create new account</legend>

  <label>account name</label>
  <%= f.text_field :name, :autofocus => true %><br />

  <label>account number</label>
  <%= f.text_field :number %><br />
  <label>parent account</label>
  <%= autofill_inputs "account", nil, "account" %><br />


 </fieldset>

 <fieldset>
  <label for="init">opening balance</label>
  <input name="init" class="money" />
  <label for="date">as of</label>
  <input name="date" id="date" />
 </fieldset>

  <%= f.submit :id => "post", :value => "create account" %>

<% end %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>
  <table>
   <caption>chart of accounts</caption>
   <tbody>
    <% totals = [] %>
    <tr>
    <% Account.columnize.map do |column| %>
     <td class="column">
      <table>
       <tbody>
        <% total = 0 %>
        <% column.each do |account| %>
        <tr>
         <% path = account.account_pathname %>
         <% path_split = path.split("|") %>
         <% indent = path_split.length-1 %>
         <% bal = account.balance %>
         <% total += bal %>
          <td>
           <span class="name" style="margin-left:<%= indent %>em">
            <a href="<%= account_path account.id %>"><%= path_split.pop %></a>
           </span>
          </td>
          <td class="balance"><%= "%.2f"%bal if bal != 0 %></td>
        </tr>
        <% end %>
        <% totals.push total %>
       </tbody>
      </table>
     </td>
    <% end %>
    </tr>
    <tr class="total">
     <td class="balance">
      <%= "%.2f"%totals[0] %>
     </td>
     <td class="balance">
      <%= "%.2f"%totals[1] %>
     </td>
    </tr>
   </tbody>
  </table>

<div><%= link_to 'New Account', new_account_path %></div>

app/views/accounts/new.html.erb
<%= render "accounts/new" %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="instance">
<table class="entries">
 <caption><%= @account.account_pathname %></caption>
 <thead>
  <tr>
   <th>date</th>
   <th>entity</th>
   <th>dr</th>
   <th>cr</th>
   <th>balance</th>
  </tr>
 </thead>
 <tbody>
  <% entries = Entry.where(account_id: @account.id).sort {|x, y| x.entry_date <=> y.entry_date} %>
  <% bal = 0 %>
  <% entries.each { |entry| %>
   <% transaktion = Transaktion.find(entry.transaktion_id) %>
   <% entity = Entity.find(transaktion.entity_id) if transaktion.entity_id %>
   <% amt = entry.price*entry.qty/100 %>
   <tr>
    <% # kludge: %>
    <td><a href="<%= transaktion_path transaktion %>"><%= transaktion.date.to_s.slice(0,10) %></a></td>
    <td>
     <% if entity %>
      <a href="<%= entity_path entity %>"><%= entity.name %></a>
     <% end %>
    </td>
    <% if entry.is_debit %>
      <% bal += amt %>
    <% else %>
      <% bal -= amt %>
    <% end %>
    <% amtfix = "%.2f"%amt %>
    <td class="money"><%= amtfix if entry.is_debit %></td>
    <td class="money"><%= amtfix if not entry.is_debit %></td>
    <td class="money"><%= "%.2f"%bal %></td>
   </tr>
  <% } %>
 </tbody>
</table>

<%= link_to 'edit this account', edit_account_path(@account) %> |
<%= link_to 'chart of accounts', accounts_path %> |
<%= link_to 'new transaction', new_transaktion_path %>
</div>